services:
  postgres:
    image: postgres:17.0-alpine
    expose:
      - 5432
    volumes:
      - boilerplate-db:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: ${DATABASE_USERNAME}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
      POSTGRES_DB: ${DATABASE_NAME}

  maildev:
    build:
      context: .
      dockerfile: maildev.Dockerfile
    expose:
      - 1080
      - 1025

  adminer:
    image: adminer
    expose:
      - 8080

  redis:
    image: redis:7-alpine
    expose:
      - 6379

  api:
    build:
      context: .
      dockerfile: Dockerfile
    expose:
      - ${APP_PORT}

volumes:
  boilerplate-db:
